# Generated by Django 4.2.4 on 2023-08-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('numero_documento', models.BigIntegerField()),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula'), ('Nit', 'Nit')], max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
