# Generated by Django 4.2.4 on 2023-09-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_alter_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('NIT', 'Nit'), ('T.I', 'Tarjeta Identidad'), ('C.E', 'Cedula Extranjera'), ('P', 'Pasaporte')], max_length=50, null=True),
        ),
    ]
